import type { Metadata } from 'next'
import { notFound } from 'next/navigation'
import { getArticleById } from '@/lib/mock-data'
import { ArticleDetailClient } from './ArticleDetailClient'
import type { Article } from '@/lib/types'

interface Props {
  params: Promise<{ id: string }>
}

// ── Hybrid article resolver ────────────────────────────────
// Order: 1. Supabase DB (Producción) 2. Mock data (Fallback)
async function resolveArticle(id: string): Promise<Article | null> {
  // Strip the pagination suffix (e.g., -p2-0) generated by InfiniteFeed mock generator
  const baseId = id.split('-p')[0] || id

  // 1. Supabase (Producción 200%)
  try {
    const { api } = await import('@/lib/api')
    const dbArticle = await api.getArticleById(baseId)
    if (dbArticle) return dbArticle
  } catch (err) {
    console.error('[article/page] supabase resolve error:', err)
  }

  // 2. Mock Data (Fallback para links antiguos generados en GDELT al vuelo)
  const mockArticle = getArticleById(baseId)
  if (mockArticle) return mockArticle

  return null
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params
  const article = await resolveArticle(id)

  if (!article) {
    return { title: 'Artículo no encontrado — VeritasAI' }
  }

  return {
    title: `${article.title} — VeritasAI`,
    description: `Análisis forense: ${article.outlet.name}. VeritasScore™: ${article.veritasScore ?? 'pendiente'}/100. ${(article.techniquesDetected ?? []).length} técnica(s) detectada(s).`,
    openGraph: {
      title: article.titleNeutralized ?? article.title,
      description: article.excerpt,
      images: article.imageUrl ? [article.imageUrl] : [],
    },
  }
}

export default async function ArticlePage({ params }: Props) {
  const { id } = await params
  const article = await resolveArticle(id)

  if (!article) {
    notFound()
  }

  return <ArticleDetailClient article={article} />
}
