import type { Metadata } from 'next'
export const dynamic = 'force-dynamic'
import { notFound } from 'next/navigation'
import { ArticleDetailClient } from './ArticleDetailClient'
import type { Article } from '@/lib/types'

interface Props {
  params: Promise<{ id: string }>
}

// ── Hybrid article resolver ────────────────────────────────
// Order: 1. Supabase DB (Producción) 2. Mock data (Fallback)
async function resolveArticle(id: string): Promise<Article | null> {
  // Strip the pagination suffix (e.g., -p2-0) generated by old InfiniteFeed mock generator
  const baseId = id.split('-p')[0] || id

  // 1. Supabase (Producción 200%)
  try {
    const { api } = await import('@/lib/api')
    const dbArticle = await api.getArticleById(baseId)
    if (dbArticle) return dbArticle
  } catch (err) {
    console.error('[article/page] supabase resolve error:', err)
  }

  // 3. Reconstrucción dinámica para GDELT/RSS (si el ID contiene la URL en base64)
  if (baseId.startsWith('gdelt-') || baseId.startsWith('rss-')) {
    try {
      const type = baseId.startsWith('gdelt-') ? 'gdelt-' : 'rss-'
      const encodedUrl = baseId.replace(type, '')
      const url = Buffer.from(encodedUrl, 'base64url').toString()
      const domain = new URL(url).hostname.replace('www.', '')
      
      return {
        id: baseId,
        url: url,
        title: "Cargando análisis forense...",
        excerpt: "Este artículo proviene de una fuente externa en tiempo real. VeritasAI está analizando el contenido ahora mismo...",
        publishedAt: new Date().toISOString(),
        outlet: {
          id: 'unknown',
          name: domain.split('.')[0].toUpperCase(),
          domain: domain,
          countryCode: 'ALL',
          currentVeritasAvg: 50
        },
        language: 'es',
        category: 'noticia',
        analysisStatus: 'pending' // Esto disparará el hook useAnalysis en el cliente
      } as Article
    } catch (e) {
      console.error('[resolveArticle] dynamic decode error:', e)
    }
  }

  return null
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { id } = await params
  const article = await resolveArticle(id)

  if (!article) {
    return { title: 'Artículo no encontrado — VeritasAI' }
  }

  return {
    title: `${article.title} — VeritasAI`,
    description: `Análisis forense: ${article.outlet.name}. VeritasScore™: ${article.veritasScore ?? 'pendiente'}/100. ${(article.techniquesDetected ?? []).length} técnica(s) detectada(s).`,
    openGraph: {
      title: article.titleNeutralized ?? article.title,
      description: article.excerpt,
      images: article.imageUrl ? [article.imageUrl] : [],
    },
  }
}

export default async function ArticlePage({ params }: Props) {
  const { id } = await params
  const article = await resolveArticle(id)

  if (!article) {
    notFound()
  }

  return <ArticleDetailClient article={article} />
}
