import type { Article, MediaOutlet, Technique } from './types'

// ── Techniques catalog (subset of 47) ─────────────────────
export const TECHNIQUES: Technique[] = [
  {
    id: 't1',
    slug: 'fear-mongering',
    name: 'Fear-mongering',
    nameEs: 'Amplificación del miedo',
    category: 'emotional',
    biopsychosocialLevel: 'biological',
    description: 'Activates amygdala before prefrontal cortex can evaluate information rationally.',
    descriptionEs: 'Activa la amígdala antes de que la corteza prefrontal pueda evaluar la información racionalmente. Titulares como "Colombia al borde del colapso" generan cortisol que sesga la interpretación de todo el artículo.',
    severity: 0.85,
    icon: '😨',
    academicSource: 'Kahneman (2011) — Thinking, Fast and Slow',
  },
  {
    id: 't2',
    slug: 'framing-effect',
    name: 'Framing Effect',
    nameEs: 'Efecto de encuadre',
    category: 'cognitive',
    biopsychosocialLevel: 'psychological',
    description: 'Same statistic presented differently activates different brain regions.',
    descriptionEs: 'La misma estadística presentada como "90% de éxito" vs "10% de fracaso" activa regiones cerebrales diferentes y produce decisiones distintas.',
    severity: 0.70,
    icon: '🖼️',
    academicSource: 'Entman (1993) — Framing Theory',
  },
  {
    id: 't3',
    slug: 'false-dichotomy',
    name: 'False Dichotomy',
    nameEs: 'Falsa dicotomía',
    category: 'cognitive',
    biopsychosocialLevel: 'psychological',
    description: 'Reduces multidimensional problems to two binary options.',
    descriptionEs: 'Reducir problemas multidimensionales a dos opciones binarías elimina el pensamiento sistémico del lector.',
    severity: 0.65,
    icon: '⚖️',
    academicSource: 'Da San Martino et al. (2020)',
  },
  {
    id: 't4',
    slug: 'moral-outrage',
    name: 'Moral Outrage Engineering',
    nameEs: 'Ingeniería de indignación moral',
    category: 'emotional',
    biopsychosocialLevel: 'social',
    description: 'Deliberately generates moral indignation to activate group identity.',
    descriptionEs: 'Genera indignación moral deliberada para activar el sistema de identidad grupal del lector, haciendo que comparta antes de analizar.',
    severity: 0.80,
    icon: '😡',
    academicSource: 'SemEval 2020 Task 11',
  },
  {
    id: 't5',
    slug: 'manufactured-consensus',
    name: 'Manufactured Consensus',
    nameEs: 'Consenso fabricado',
    category: 'narrative',
    biopsychosocialLevel: 'social',
    description: 'Only citing sources that confirm a position to create appearance of unanimity.',
    descriptionEs: 'Citar solo fuentes que confirman una posición para crear apariencia de unanimidad.',
    severity: 0.60,
    icon: '🎭',
    academicSource: 'Da San Martino et al. (2020)',
  },
  {
    id: 't6',
    slug: 'nominalization',
    name: 'Nominalization',
    nameEs: 'Nominalización',
    category: 'neurolinguistic',
    biopsychosocialLevel: 'psychological',
    description: 'Converting processes into entities eliminates responsibility and agent.',
    descriptionEs: 'Convertir procesos en entidades ("la violencia crece" en lugar de "grupo X hizo Y") elimina la responsabilidad y el agente.',
    severity: 0.50,
    icon: '🔤',
    academicSource: 'Da San Martino et al. (2020)',
  },
  {
    id: 't7',
    slug: 'strategic-omission',
    name: 'Strategic Omission',
    nameEs: 'Omisión estratégica',
    category: 'narrative',
    biopsychosocialLevel: 'psychological',
    description: 'What is NOT said is frequently more manipulative than what IS said.',
    descriptionEs: 'Lo que NO se dice es frecuentemente más manipulador que lo que sí se dice.',
    severity: 0.75,
    icon: '🕳️',
    academicSource: 'BABE dataset — Raza et al. (2022)',
  },
  {
    id: 't8',
    slug: 'biometric-copy',
    name: 'Biometric-Optimized Copy',
    nameEs: 'Texto optimizado biométricamente',
    category: 'neuromarketing',
    biopsychosocialLevel: 'biological',
    description: 'Using high-contrast phonemes and rhythmic patterns to bypass rational filters.',
    descriptionEs: 'Uso de fonemas de alto contraste y patrones rítmicos para bypassar filtros racionales y generar impronta emocional inmediata.',
    severity: 0.90,
    icon: '🧠',
    academicSource: 'Neuromarketing Science & Business Association (2023)',
  }
]

// ── Media Outlets (Mock Data) ─────────────────────────────
export const MEDIA_OUTLETS: MediaOutlet[] = [
  {
    id: 'm1', name: 'Semana', domain: 'semana.com', countryCode: 'CO',
    currentVeritasAvg: 78, articlesAnalyzed: 12450, alertLevel: 'red',
    politicalBiasScore: 0.8, reliabilityScore: 0.45,
    topTechniques: ['fear-mongering', 'moral-outrage', 'false-dichotomy'],
    credScore: 0.42,
  },
  {
    id: 'm2', name: 'La Silla Vacía', domain: 'lasillavacia.com', countryCode: 'CO',
    currentVeritasAvg: 22, articlesAnalyzed: 8900, alertLevel: 'green',
    politicalBiasScore: -0.1, reliabilityScore: 0.88,
    topTechniques: ['framing-effect'],
    credScore: 0.89,
  },
  {
    id: 'm3', name: 'El Espectador', domain: 'elespectador.com', countryCode: 'CO',
    currentVeritasAvg: 34, articlesAnalyzed: 15600, alertLevel: 'yellow',
    politicalBiasScore: -0.3, reliabilityScore: 0.75,
    topTechniques: ['framing-effect', 'nominalization'],
    credScore: 0.78,
  },
  {
    id: 'm4', name: 'El Tiempo', domain: 'eltiempo.com', countryCode: 'CO',
    currentVeritasAvg: 41, articlesAnalyzed: 22300, alertLevel: 'yellow',
    politicalBiasScore: 0.2, reliabilityScore: 0.72,
    topTechniques: ['framing-effect', 'manufactured-consensus'],
    credScore: 0.74,
  },
  {
    id: 'm5', name: 'Caracol Radio', domain: 'caracol.com.co', countryCode: 'CO',
    currentVeritasAvg: 45, articlesAnalyzed: 18900, alertLevel: 'yellow',
    politicalBiasScore: 0.1, reliabilityScore: 0.68,
    topTechniques: ['moral-outrage'],
    credScore: 0.70,
  },
  {
    id: 'm6', name: 'Univisión', domain: 'univision.com', countryCode: 'US',
    currentVeritasAvg: 14, articlesAnalyzed: 412, alertLevel: 'green',
    politicalBiasScore: 0, reliabilityScore: 0.93,
    topTechniques: [],
    credScore: 0.92,
  },
  {
    id: 'm7', name: 'Infobae', domain: 'infobae.com', countryCode: 'AR',
    currentVeritasAvg: 55, articlesAnalyzed: 4210, alertLevel: 'orange',
    politicalBiasScore: 0.4, reliabilityScore: 0.50,
    topTechniques: ['fear-mongering', 'framing-effect', 'biometric-copy'],
    credScore: 0.48,
  },
  {
    id: 'm8', name: 'El País', domain: 'elpais.com', countryCode: 'ES',
    currentVeritasAvg: 28, articlesAnalyzed: 5890, alertLevel: 'green',
    politicalBiasScore: -0.2, reliabilityScore: 0.80,
    topTechniques: ['framing-effect'],
    credScore: 0.82,
  },
  {
    id: 'm9', name: 'The New York Times', domain: 'nytimes.com', countryCode: 'US',
    currentVeritasAvg: 22, articlesAnalyzed: 12500, alertLevel: 'green',
    politicalBiasScore: -0.15, reliabilityScore: 0.92,
    topTechniques: ['framing-effect'],
    credScore: 0.94,
  },
  {
    id: 'm10', name: 'CNN', domain: 'cnn.com', countryCode: 'US',
    currentVeritasAvg: 38, articlesAnalyzed: 15400, alertLevel: 'yellow',
    politicalBiasScore: -0.3, reliabilityScore: 0.78,
    topTechniques: ['moral-outrage', 'framing-effect'],
    credScore: 0.75,
  },
  {
    id: 'm11', name: 'Fox News', domain: 'foxnews.com', countryCode: 'US',
    currentVeritasAvg: 65, articlesAnalyzed: 14200, alertLevel: 'orange',
    politicalBiasScore: 0.45, reliabilityScore: 0.52,
    topTechniques: ['fear-mongering', 'moral-outrage', 'strategic-omission'],
    credScore: 0.49,
  },
  {
    id: 'm12', name: 'Reuters', domain: 'reuters.com', countryCode: 'UK',
    currentVeritasAvg: 12, articlesAnalyzed: 45600, alertLevel: 'green',
    politicalBiasScore: 0, reliabilityScore: 0.96,
    topTechniques: [],
    credScore: 0.97,
  },
  {
    id: 'm13', name: 'Associated Press', domain: 'apnews.com', countryCode: 'US',
    currentVeritasAvg: 15, articlesAnalyzed: 38900, alertLevel: 'green',
    politicalBiasScore: 0, reliabilityScore: 0.95,
    topTechniques: [],
    credScore: 0.96,
  },
  {
    id: 'm14', name: 'BBC News', domain: 'bbc.com', countryCode: 'UK',
    currentVeritasAvg: 25, articlesAnalyzed: 52100, alertLevel: 'green',
    politicalBiasScore: -0.1, reliabilityScore: 0.89,
    topTechniques: ['framing-effect'],
    credScore: 0.90,
  },
  {
    id: 'm15', name: 'The Guardian', domain: 'theguardian.com', countryCode: 'UK',
    currentVeritasAvg: 32, articlesAnalyzed: 28400, alertLevel: 'yellow',
    politicalBiasScore: -0.4, reliabilityScore: 0.82,
    topTechniques: ['framing-effect', 'moral-outrage'],
    credScore: 0.84,
  },
  {
    id: 'm16', name: 'Wall Street Journal', domain: 'wsj.com', countryCode: 'US',
    currentVeritasAvg: 29, articlesAnalyzed: 31200, alertLevel: 'green',
    politicalBiasScore: 0.3, reliabilityScore: 0.85,
    topTechniques: ['framing-effect'],
    credScore: 0.87,
  },
  {
    id: 'm17', name: 'Al Jazeera', domain: 'aljazeera.com', countryCode: 'QA',
    currentVeritasAvg: 42, articlesAnalyzed: 19800, alertLevel: 'yellow',
    politicalBiasScore: -0.2, reliabilityScore: 0.70,
    topTechniques: ['strategic-omission', 'framing-effect'],
    credScore: 0.72,
  },
  {
    id: 'm18', name: 'Bloomberg', domain: 'bloomberg.com', countryCode: 'US',
    currentVeritasAvg: 18, articlesAnalyzed: 65400, alertLevel: 'green',
    politicalBiasScore: 0.1, reliabilityScore: 0.94,
    topTechniques: [],
    credScore: 0.95,
  },
  {
    id: 'm19', name: 'France 24', domain: 'france24.com', countryCode: 'FR',
    currentVeritasAvg: 21, articlesAnalyzed: 12300, alertLevel: 'green',
    politicalBiasScore: -0.05, reliabilityScore: 0.90,
    topTechniques: [],
    credScore: 0.91,
  },
  {
    id: 'm20', name: 'RT (Russia Today)', domain: 'rt.com', countryCode: 'RU',
    currentVeritasAvg: 88, articlesAnalyzed: 25600, alertLevel: 'red',
    politicalBiasScore: 0.9, reliabilityScore: 0.25,
    topTechniques: ['fear-mongering', 'manufactured-consensus', 'strategic-omission', 'biometric-copy'],
    credScore: 0.22,
  },
  {
    id: 'm21', name: 'Telesur', domain: 'telesurtv.net', countryCode: 'VE',
    currentVeritasAvg: 85, articlesAnalyzed: 14200, alertLevel: 'red',
    politicalBiasScore: -0.9, reliabilityScore: 0.30,
    topTechniques: ['manufactured-consensus', 'moral-outrage', 'strategic-omission'],
    credScore: 0.28,
  },
  {
    id: 'm22', name: 'Clarín', domain: 'clarin.com', countryCode: 'AR',
    currentVeritasAvg: 48, articlesAnalyzed: 34500, alertLevel: 'yellow',
    politicalBiasScore: 0.4, reliabilityScore: 0.65,
    topTechniques: ['moral-outrage', 'framing-effect'],
    credScore: 0.68,
  },
  {
    id: 'm23', name: 'O Globo', domain: 'oglobo.globo.com', countryCode: 'BR',
    currentVeritasAvg: 36, articlesAnalyzed: 41200, alertLevel: 'yellow',
    politicalBiasScore: 0.2, reliabilityScore: 0.78,
    topTechniques: ['framing-effect'],
    credScore: 0.80,
  },
  {
    id: 'm24', name: 'El Universal', domain: 'eluniversal.com.mx', countryCode: 'MX',
    currentVeritasAvg: 44, articlesAnalyzed: 28900, alertLevel: 'yellow',
    politicalBiasScore: 0.1, reliabilityScore: 0.70,
    topTechniques: ['moral-outrage'],
    credScore: 0.72,
  },
  {
    id: 'm25', name: 'The Washington Post', domain: 'washingtonpost.com', countryCode: 'US',
    currentVeritasAvg: 24, articlesAnalyzed: 39400, alertLevel: 'green',
    politicalBiasScore: -0.2, reliabilityScore: 0.90,
    topTechniques: ['framing-effect'],
    credScore: 0.91,
  },
]

// ── Articles (realistic mock data) ────────────────────────
export const MOCK_ARTICLES: Article[] = [
  {
    id: 'a1',
    url: 'https://semana.com/nacion/articulo/economia-colombiana-crisis-petro-2026',
    title: 'Colombia al borde del colapso económico: expertos advierten catástrofe bajo Petro',
    titleNeutralized: 'Economía colombiana creció 1.2% en Q1 2026, por debajo del 2.8% proyectado',
    excerpt: 'El país enfrenta su peor crisis financiera en décadas mientras el gobierno insiste en reformas impopulares que amenazan el tejido productivo nacional.',
    imageUrl: null, 
    outlet: MEDIA_OUTLETS[0]!,
    journalist: 'Carlos Mendoza',
    journalistScore: 68,
    publishedAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    category: 'noticia',
    countryCode: 'CO',
    language: 'es',
    veritasScore: 73,
    analysisStatus: 'completed',
    analysisConfidence: 0.87,
    viewCount: 12450,
    trendingScore: 0.95,
    tags: ['economy', 'politics', 'colombia'],
    analysisLogs: [
      { stepId: 'nlp', status: 'completed', timestamp: '0.1s', technicalDetail: 'Parsing currency values ($4.300) and exchange rate entities.', technicalDetailEs: 'Procesando valores de moneda ($4.300) y entidades de tasa de cambio.' },
      { stepId: 'bert', status: 'completed', timestamp: '0.4s', technicalDetail: 'Identifying panic-inducing exclamation patterns in the lead.', technicalDetailEs: 'Identificando patrones de pánico en exclamaciones del inicio.' },
      { stepId: 'llama', status: 'completed', timestamp: '2.0s', technicalDetail: 'Checking "record" claim. Local 6-month high verified.', technicalDetailEs: 'Verificando afirmación de "récord". Máximo local de 6 meses verificado.' },
      { stepId: 'rewrite', status: 'completed', timestamp: '3.1s', technicalDetail: 'Neutralizing "pánico" and "alarma" to technical volatility terms.', technicalDetailEs: 'Neutralizando "pánico" y "alarma" a términos de volatilidad técnica.' },
      { stepId: 'factcheck', status: 'completed', timestamp: '4.7s', technicalDetail: 'TRM average confirmed at $4.280 via Central Bank API.', technicalDetailEs: 'Promedio TRM confirmado en $4.280 vía API del Banco Central.' },
    ],
    techniquesDetected: [
      {
        technique: TECHNIQUES[0]!,
        quote: 'Colombia al borde del colapso económico',
        confidence: 0.93,
        explanation: 'El titular usa vocabulario de catástrofe extrema ("colapso") para activar la amígdala antes de que el lector pueda evaluar racionalmente los datos económicos reales, que son de crecimiento moderado.',
      },
      {
        technique: TECHNIQUES[1]!,
        quote: 'reformas impopulares que amenazan el tejido productivo',
        confidence: 0.78,
        explanation: 'El framing reduce la agenda económica del gobierno a una amenaza unidimensional, omitiendo perspectivas alternativas sobre las reformas.',
      },
      {
        technique: TECHNIQUES[6]!,
        quote: 'peor crisis financiera en décadas',
        confidence: 0.82,
        explanation: 'Se omite que el PIB creció 1.2% y que varios indicadores macroeconómicos están dentro de rangos históricos normales.',
      },
    ],
    content: "La economía colombiana se encuentra en un punto de inflexión crítico que ha encendido todas las alarmas en el sector financiero. Según diversos analistas de los principales bancos de inversión, Colombia al borde del colapso económico debido a la profunda incertidumbre generada por las recientes propuestas legislativas en materia de pensiones y salud. El país enfrenta su peor crisis financiera en décadas mientras el gobierno insiste en reformas impopulares que amenazan el tejido productivo nacional y la confianza de los inversionistas extranjeros.\n\nDurante el último trimestre, el PIB mostró una desaceleración más pronunciada de lo previsto, situándose apenas en el 1.2%. Expertos advierten catástrofe bajo Petro si no se ajusta el rumbo fiscal de manera inmediata, señalando que la fuga de capitales ha alcanzado niveles récord. Sin embargo, desde el Ministerio de Hacienda se argumenta que estos movimientos son parte de una transición necesaria hacia una economía menos dependiente del extractivismo.\n\nEn los hogares, la preocupación es palpable. El costo de vida sigue sin ceder y las tasas de interés se mantienen en niveles restrictivos, lo que ha frenado el consumo interno. La narrativa de la crisis se ha instalado en el discurso público, alimentada por titulares que vaticinan un escenario de estanflación si no se toman medidas correctivas urgentes antes de finalizar el año fiscal. La caída en la inversión extranjera directa, que se redujo un 15% según los últimos reportes, es vista por la oposición como una señal inequívoca de que el modelo económico actual está agotado y requiere un cambio de timón antes de que el daño sea irreversible para las próximas generaciones.",
    contentNeutralized: "El Departamento Administrativo Nacional de Estadística (DANE) reportó un crecimiento del Producto Interno Bruto (PIB) del 1.2% para el último trimestre, una cifra que refleja una desaceleración en comparación con periodos anteriores. Diversos sectores financieros han expresado su opinión sobre el impacto de las reformas de pensiones y salud en el mercado, mientras que el Ministerio de Hacienda sostiene que estos cambios son estructurales para la diversificación económica.\n\nAunque la inversión extranjera ha mostrado fluctuaciones, los analistas sugieren que el país está en un periodo de ajuste fiscal. El costo de vida y las tasas de interés continúm siendo temas centrales en la agenda económica nacional, con el Banco de la República manteniendo una postura cautelosa para controlar la inflación. Los informes técnicos indican que, si bien el crecimiento es menor al proyectado, los indicadores macroeconómicos fundamentales permanecen dentro de los márgenes de estabilidad observados en la última década.",
    summaryNeutralized: "El PIB de Colombia creció un 1.2% en el último trimestre, cifra que se sitúa por debajo de las expectativas iniciales de los analistas. Si bien el sector financiero expresa cautela ante las reformas gubernamentales en curso, los indicadores macroeconómicos actuales mantienen una estabilidad relativa.",
    primaryIntent: 'persuade',
  },
  {
    id: 'a2',
    url: 'https://lasillavacia.com/politica/coalicion-gobierno-peticionario-senado',
    title: 'La coalición de Petro en el Senado pierde su tercera votación clave del mes',
    titleNeutralized: 'Reforma pensional es rechazada en votación del Senado por 56 votos contra 47',
    excerpt: 'El proyecto de reforma pensional fue derrotado por 56 votos contra 47, en lo que analistas ven como señal del reordenamiento de alianzas políticas.',
    imageUrl: null, 
    outlet: MEDIA_OUTLETS[1]!,
    journalist: 'Juanita Goebertus',
    journalistScore: 18,
    publishedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    category: 'analisis',
    countryCode: 'CO',
    language: 'es',
    veritasScore: 17,
    analysisStatus: 'completed',
    analysisConfidence: 0.91,
    viewCount: 8320,
    trendingScore: 0.82,
    tags: ['politics', 'elections', 'colombia'],
    analysisLogs: [
      { stepId: 'nlp', status: 'completed', timestamp: '0.1s', technicalDetail: 'Parsing Senate voting metadata and party affiliations.', technicalDetailEs: 'Procesando metadatos de votación del Senado y afiliaciones partidistas.' },
      { stepId: 'bert', status: 'completed', timestamp: '0.5s', technicalDetail: 'Detecting neutrality in lexical choices (Score: 0.11).', technicalDetailEs: 'Detectando neutralidad en elecciones léxicas (Score: 0.11).' },
      { stepId: 'llama', status: 'completed', timestamp: '2.2s', technicalDetail: 'Cross-referencing 56/47 vote count with official Senate records.', technicalDetailEs: 'Contrastando conteo de votos 56/47 con registros oficiales del Senado.' },
      { stepId: 'rewrite', status: 'completed', timestamp: '3.0s', technicalDetail: 'Ensuring factual accuracy in technical legislative terms.', technicalDetailEs: 'Asegurando precisión factual en términos legislativos técnicos.' },
      { stepId: 'factcheck', status: 'completed', timestamp: '4.6s', technicalDetail: 'Confirmed: Reform rejected in first debate as reported.', technicalDetailEs: 'Confirmado: Reforma rechazada en primer debate según lo reportado.' },
    ],
    techniquesDetected: [],
    content: "En una jornada marcada por intensos debates y una asistencia casi total de las bancadas, el Senado de la República hundió definitivamente el proyecto de reforma pensional presentado por el Gobierno Nacional. La votación, que se saldó con 56 votos por el no y 47 por el sí, representa la tercera derrota legislativa de gran calado para la administración Petro en menos de un mes.\n\nEl debate se centró en el umbral de cotización obligatoria en Colpensiones, uno de los puntos más polémicos del articulado. Mientras el gobierno defendía un umbral de tres salarios mínimos, la oposición y sectores independientes argumentaron que esto ponía en riesgo la sostenibilidad fiscal del país a largo plazo. La falta de consenso llevó a que varios senadores que anteriormente habían apoyado iniciativas oficiales, esta vez optaran por el voto negativo o la abstención.\n\nTras el resultado, el Ministro del Interior manifestó su descontento, señalando que se ha perdido una oportunidad histórica para ampliar la cobertura de protección a la vejez. Por su parte, los sectores de oposición celebraron el resultado como un 'triunfo de la sensatez financiera'. Analistas políticos sugieren que este resultado obligará al ejecutivo a replantear su estrategia de coaliciones, ya que los apoyos que parecían sólidos al inicio de la legislatura se han vuelto volátiles.",
    contentNeutralized: "El Senado de la República rechazó el proyecto de reforma pensional del Gobierno Nacional con una votación de 56 a 47. El punto principal de desacuerdo fue el umbral de cotización obligatoria para el sistema público, donde las propuestas variaban entre 1.5 y 3 salarios mínimos.\n\nEl resultado legislativo implica que el proyecto actual no continuará su trámite, lo que obliga a las partes a considerar nuevos acercamientos o la presentación de una nueva iniciativa en el futuro. Los observadores señalan que la dinámica de votos en el Senado refleja una división técnica sobre la sostenibilidad del sistema de pensiones a largo plazo.",
    summaryNeutralized: "La reforma pensional no alcanzó los votos necesarios en el Senado. El rechazo se debió principalmente a preocupaciones sobre la sostenibilidad fiscal del modelo propuesto.",
    primaryIntent: 'inform',
  },
  {
    id: 'a3',
    url: 'https://elespectador.com/colombia/violencia-masacre-cauca-guerrilla',
    title: 'Nueva masacre en el Cauca: el terror que nunca para en Colombia',
    titleNeutralized: 'Tres personas asesinadas en el municipio de Argelia, Cauca — autoridades investigan',
    excerpt: 'El horror de la violencia armada volvió a golpe al deprimido departamento del Cauca, donde grupos al margen de la ley siembran pánico entre comunidades indefensas.',
    imageUrl: null, 
    outlet: MEDIA_OUTLETS[2]!,
    journalist: 'Santiago Torrado',
    journalistScore: 42,
    publishedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    category: 'noticia',
    countryCode: 'CO',
    language: 'es',
    veritasScore: 54,
    analysisStatus: 'completed',
    analysisConfidence: 0.79,
    viewCount: 23100,
    trendingScore: 0.98,
    tags: ['security', 'human_rights', 'colombia'],
    analysisLogs: [
      { stepId: 'nlp', status: 'completed', timestamp: '0.1s', technicalDetail: 'Identifying locations (Argelia, Cauca) and casualty count (3).', technicalDetailEs: 'Identificando ubicaciones (Argelia, Cauca) y conteo de víctimas (3).' },
      { stepId: 'bert', status: 'completed', timestamp: '0.7s', technicalDetail: 'Emotional intensity check on "horror" and "terror". High arousal confirmed.', technicalDetailEs: 'Verificación de intensidad emocional en "horror" y "terror". Alta excitación confirmada.' },
      { stepId: 'llama', status: 'completed', timestamp: '2.5s', technicalDetail: 'Correlating with Ombudsman alerts (Alertas Tempranas) for the region.', technicalDetailEs: 'Correlacionando con alertas de la Defensoría (Alertas Tempranas) para la región.' },
      { stepId: 'rewrite', status: 'completed', timestamp: '3.4s', technicalDetail: 'Removing moral engineering from headline to focus on factual reporting.', technicalDetailEs: 'Eliminando ingeniería moral del titular para enfocar en el reporte factual.' },
      { stepId: 'factcheck', status: 'completed', timestamp: '5.1s', technicalDetail: 'Confirmed massacre location and victim status via local reports.', technicalDetailEs: 'Confirmada ubicación de masacre y estatus de víctimas vía reportes locales.' },
    ],
    techniquesDetected: [
      {
        technique: TECHNIQUES[3]!,
        quote: 'el terror que nunca para',
        confidence: 0.88,
        explanation: 'La frase en el titular ingeniería indignación moral usando lenguaje absoluto y carga emocional extrema.',
      },
      {
        technique: TECHNIQUES[5]!,
        quote: 'la violencia armada volvió a golpear',
        confidence: 0.71,
        explanation: '"La violencia" como agente elimina específicamente quiénes actores armados perpetraron el hecho.',
      },
    ],
    content: "Las comunidades rurales del municipio de Argelia, en el departamento del Cauca, se encuentran nuevamente sumidas en el luto tras el hallazgo de tres cuerpos sin vida en un paraje conocido como El Plateado. El horror de la violencia armada volvió a golpear a esta región, donde grupos al margen de la ley como las disidencias de las FARC y el ELN se disputan el control de las rutas del narcotráfico y la minería ilegal.\n\nSegún los primeros informes de las autoridades locales, las víctimas eran residentes de la zona que habrían sido interceptadas por hombres armados mientras se movilizaban por una vía veredal. Hasta el momento, no se han establecido los móviles exactos del crimen, pero la Defensoría del Pueblo ya había emitido alertas tempranas sobre el riesgo inminente para la población civil debido a la presencia de estos actores armados.\n\nEl gobierno departamental ha convocado a un consejo de seguridad extraordinario para analizar la situación y desplegar mayor presencia militar en la zona. Sin embargo, los líderes sociales del Cauca insisten en que la solución no es solo militar, sino que se requiere una inversión social profunda para arrebatarle los jóvenes a la guerra y ofrecer alternativas económicas reales en un departamento que históricamente se ha sentido abandonado por el estado central.",
    contentNeutralized: "Tres personas fueron halladas sin vida en Argelia, Cauca, en una zona donde se ha reportado presencia de diversos grupos armados ilegales. La Fiscalía General de la Nación ha iniciado las investigaciones pertinentes para identificar a las víctimas y determinar los autores del hecho.\n\nLa Defensoría del Pueblo mantiene activa una alerta temprana para esta región debido a los riesgos derivados de los conflictos por el control territorial entre grupos armados. Las autoridades locales han solicitado el fortalecimiento de la seguridad y el inicio de mesas de diálogo comunitario para atender las necesidades de la población afectada por la inseguridad.",
    summaryNeutralized: "Autoridades investigan el asesinato de tres personas en el Cauca. El hecho ocurre en una región con presencia histórica de grupos armados ilegales y alertas activas de la Defensoría del Pueblo.",
    primaryIntent: 'inform',
  },
  {
    id: 'a4',
    url: 'https://univision.com/noticias/mundo/elecciones-venezuela-oposicion-unidad',
    title: 'Oposición venezolana logra acuerdo histórico: un solo candidato para enfrentar a Maduro',
    titleNeutralized: 'Plataforma Unitaria de Venezuela inscribe candidato de consenso para elecciones presidenciales',
    excerpt: 'En un giro inesperado, las principales fuerzas democráticas de Venezuela han dejado de lado sus diferencias para presentar un frente unido ante el chavismo.',
    imageUrl: null, 
    outlet: MEDIA_OUTLETS[5]!,
    journalist: 'Elyangélica González',
    journalistScore: 25,
    publishedAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    category: 'noticia',
    countryCode: 'US',
    language: 'es',
    veritasScore: 14,
    analysisStatus: 'completed',
    analysisConfidence: 0.95,
    viewCount: 45200,
    trendingScore: 0.92,
    tags: ['politics', 'international'],
    analysisLogs: [
      { stepId: 'nlp', status: 'completed', timestamp: '0.1s', technicalDetail: 'Extracting key entity: "Plataforma Unitaria Democrática".', technicalDetailEs: 'Extrayendo entidad clave: "Plataforma Unitaria Democrática".' },
      { stepId: 'bert', status: 'completed', timestamp: '0.4s', technicalDetail: 'Bias detection score: 0.08 (highly objective narrative).', technicalDetailEs: 'Puntaje de detección de sesgo: 0.08 (narrativa altamente objetiva).' },
      { stepId: 'llama', status: 'completed', timestamp: '1.9s', technicalDetail: 'Verifying candidate consensus status across international wires.', technicalDetailEs: 'Verificando estatus de consenso de candidatos en agencias internacionales.' },
      { stepId: 'rewrite', status: 'completed', timestamp: '2.8s', technicalDetail: 'Minor adjustment to "historic" framing to maintain technical neutrality.', technicalDetailEs: 'Ajuste menor al encuadre de "histórico" para mantener neutralidad técnica.' },
      { stepId: 'factcheck', status: 'completed', timestamp: '4.2s', technicalDetail: 'CNE registration window confirmed open for consensus candidates.', technicalDetailEs: 'Ventana de registro del CNE confirmada abierta para candidatos de consenso.' },
    ],
    techniquesDetected: [],
    content: "Tras semanas de intensas negociaciones a puerta cerrada, la Plataforma Unitaria Democrática anunció hoy la designación de un candidato único para las próximas elecciones presidenciales en Venezuela. Este acuerdo histórico representa un hito para las fuerzas opositoras, que en el pasado se han visto fragmentadas por diferencias ideológicas y estratégicas. La unidad lograda busca ofrecer una alternativa sólida ante el gobierno de Nicolás Maduro.\n\nEl candidato seleccionado, cuya trayectoria ha sido descrita como técnica y moderada, ha recibido el respaldo de los principales líderes políticos que se encuentran tanto dentro como fuera del país. La comunidad internacional, incluyendo a Estados Unidos y la Unión Europea, ha saludado el anuncio como un paso positivo hacia una salida democrática y pacífica a la crisis venezolana. Las encuestas preliminares sugieren que un frente unido aumenta significativamente las posibilidades de la oposición en los comicios.\n\nSin embargo, el camino hacia las urnas sigue lleno de obstáculos. Las autoridades electorales venezolanas han impuesto diversas restricciones administrativas a varios partidos de la coalición, y la inhabilitación de figuras clave sigue siendo un tema de preocupación global. A pesar de esto, el optimismo ha crecido entre los votantes, quienes ven en este consenso una oportunidad real de cambio después de más de dos décadas de chavismo.",
    contentNeutralized: "La Plataforma Unitaria Democrática de Venezuela ha formalizado la inscripción de un candidato de consenso para los próximos comicios presidenciales. La decisión se tomó tras un proceso de deliberación interna entre los diversos partidos que conforman la coalición opositora, con el objetivo de unificar la oferta electoral.\n\nEl anuncio ha sido seguido por reacciones de diversos organismos internacionales, quienes monitorean el desarrollo del proceso electoral venezolano. Se espera que la campaña se centre en propuestas de recuperación económica y estabilidad institucional. Las autoridades electorales continúan con el cronograma establecido, mientras la coalición opositora trabaja en la organización de su red de testigos y voluntarios para la jornada de votación.",
    summaryNeutralized: "La oposición venezolana inscribió un candidato único para las elecciones presidenciales tras alcanzar un acuerdo interno. La medida busca consolidar un frente común para la próxima jornada electoral.",
    primaryIntent: 'inform',
  },
  {
    id: 'a5',
    url: 'https://infobae.com/america/colombia/2026/04/21/excombatientes-farc-cordoba-seguimiento',
    title: 'La verdad oculta tras la reincorporación: el fracaso de los acuerdos en el sur de Córdoba',
    titleNeutralized: 'Informe académico analiza estado de proyectos productivos de ex-combatientes en Córdoba',
    excerpt: 'Un estudio revela que el 80% de los ex-guerrilleros en la zona han abandonado sus proyectos productivos debido a la falta de garantías estatales.',
    imageUrl: null, 
    outlet: MEDIA_OUTLETS[6]!,
    journalist: 'Roberto Navarro',
    journalistScore: 55,
    publishedAt: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    category: 'investigacion',
    countryCode: 'CO',
    language: 'es',
    veritasScore: 12,
    analysisStatus: 'completed',
    analysisConfidence: 0.95,
    viewCount: 4120,
    trendingScore: 0.45,
    tags: ['security', 'human_rights', 'justice', 'colombia'],
    analysisLogs: [
      { stepId: 'nlp', status: 'completed', timestamp: '0.1s', technicalDetail: 'Tracking entity: "reincorporados" and geography: "Córdoba".', technicalDetailEs: 'Rastreando entidad: "reincorporados" y geografía: "Córdoba".' },
      { stepId: 'bert', status: 'completed', timestamp: '0.5s', technicalDetail: 'Academic tone detected (0.92). Structural bias low.', technicalDetailEs: 'Tono académico detectado (0.92). Sesgo estructural bajo.' },
      { stepId: 'llama', status: 'completed', timestamp: '2.4s', technicalDetail: 'Comparing 80% abandonment claim vs University report (65% success).', technicalDetailEs: 'Comparando cifra de 80% abandono vs reporte de Universidad (65% éxito).' },
      { stepId: 'rewrite', status: 'completed', timestamp: '3.2s', technicalDetail: 'Debiasing "fracaso" narrative based on factual project success rates.', technicalDetailEs: 'Neutralizando narrativa de "fracaso" basada en tasas reales de éxito.' },
      { stepId: 'factcheck', status: 'completed', timestamp: '4.9s', technicalDetail: 'University of Córdoba source confirmed. Data discrepancy identified.', technicalDetailEs: 'Fuente de Universidad de Córdoba confirmada. Discrepancia identificada.' },
    ],
    techniquesDetected: [],
    content: "Un exhaustivo informe de seguimiento realizado por la Universidad de Córdoba ha arrojado luces sobre la realidad de 847 ex-combatientes de las FARC que iniciaron su proceso de reincorporación tras la firma de los acuerdos de paz. Cinco años después, el panorama muestra una mezcla de éxitos agrícolas y persistentes desafíos de seguridad que varían significativamente según el municipio.\n\nEl estudio destaca que el 65% de los participantes ha logrado establecer proyectos productivos sostenibles, principalmente en la siembra de cacao y café especial. Sin embargo, el acceso a tierras tituladas sigue siendo la principal barrera para la estabilidad a largo plazo. 'La voluntad de paz es total, pero la burocracia para la adjudicación de baldíos está retrasando los sueños de muchos campesinos que dejaron las armas', señala el informe.\n\nEn materia de seguridad, la situación es más compleja. En municipios como Tierralta y Montelíbano, la presencia de otros grupos armados ha limitado la movilidad y el liderazgo de los reincorporados. A pesar de esto, el tejido social se ha ido fortaleciendo mediante cooperativas que no solo benefician a los ex-combatientes, sino a toda la comunidad local, demostrando que la paz territorial es posible cuando existe acompañamiento académico y social constante.",
    contentNeutralized: "Un informe de la Universidad de Córdoba analiza el estado de la reincorporación de 847 antiguos miembros de las FARC. Los datos indican que la mayoría participa en proyectos agrícolas sostenibles, aunque persisten retos relacionados con la titulación de tierras y la seguridad en ciertas áreas rurales.\n\nEl documento resalta la importancia de la colaboración entre la academia y las comunidades locales para el éxito de los procesos de paz. Se recomienda agilizar los trámites administrativos para la propiedad de la tierra y fortalecer las garantías de seguridad en los municipios con presencia de actores armados ilegales para consolidar los resultados obtenidos hasta ahora.",
    summaryNeutralized: "Estudio universitario revela avances en proyectos productivos de ex-combatientes en Córdoba, pero advierte sobre barreras administrativas y riesgos de seguridad persistentes.",
    primaryIntent: 'inform',
  },
  {
    id: 'a6',
    url: 'https://caracol.com.co/nacion/2026/04/21/dolar-historico-colombia',
    title: '¡Alarma! El dólar rompe récord histórico y los colombianos lo pagarán caro',
    titleNeutralized: 'El peso colombiano alcanza mínimo de 6 meses: tasa de cambio cierra en $4,280 COP/USD',
    excerpt: 'La divisa estadounidense superó los $4.300 pesos, generando pánico en los mercados y preocupación en hogares que dependen de importaciones básicas.',
    imageUrl: null, 
    outlet: MEDIA_OUTLETS[4]!,
    journalist: 'Andrés Felipe Cárdenas',
    journalistScore: 48,
    publishedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    category: 'noticia',
    countryCode: 'CO',
    language: 'es',
    veritasScore: 61,
    analysisStatus: 'completed',
    analysisConfidence: 0.82,
    viewCount: 31200,
    trendingScore: 0.99,
    tags: ['economy', 'colombia'],
    techniquesDetected: [
      {
        technique: TECHNIQUES[0]!,
        quote: '¡Alarma! El dólar rompe récord histórico',
        confidence: 0.95,
        explanation: '"¡Alarma!" al inicio del titular crea respuesta de urgencia antes de que el lector conozca el contexto.',
      },
      {
        technique: TECHNIQUES[6]!,
        quote: 'generando pánico en los mercados',
        confidence: 0.74,
        explanation: 'Se omite que la variación del peso es de 1.2%, en línea con movimientos regionales del día.',
      },
    ],
    content: "La divisa estadounidense superó los $4.300 pesos hoy en la Bolsa de Valores de Colombia, marcando un hito que no se veía desde hace seis meses. ¡Alarma! El dólar rompe récord histórico y los colombianos lo pagarán caro, especialmente en la canasta básica y en los servicios que dependen de insumos importados. Esta situación está generando pánico en los mercados internacionales y preocupación en hogares que dependen de remesas e importaciones.\n\nEl movimiento, que tomó por sorpresa a muchos operadores, se dio en medio de una jornada de alta volatilidad en los mercados emergentes. Mientras algunos analistas atribuyen el alza a la incertidumbre política local, otros señalan que el fortalecimiento global del dólar es el factor determinante. La divisa cerró en un promedio de $4.280, pero alcanzó picos de pánico durante la mañana que activaron los mecanismos de intervención del Banco de la República.\n\nPara el ciudadano de a pie, este incremento se traducirá en un encarecimiento de productos tecnológicos, vehículos y alimentos importados. El gobierno ha pedido calma, asegurando que los fundamentos macroeconómicos del país son sólidos, pero la percepción de riesgo país sigue al alza en los índices de Wall Street.",
    contentNeutralized: "La tasa de cambio en Colombia cerró en un promedio de $4.280 COP/USD, tras una jornada de volatilidad influenciada por la tendencia alcista del dólar a nivel global. Aunque se alcanzó el punto más alto del semestre, las autoridades económicas monitorean la situación para asegurar la estabilidad cambiaria frente a las fluctuaciones del mercado internacional.\n\nEl comportamiento del peso colombiano está alineado con movimientos similares en otras monedas de economías emergentes, respondiendo a factores macroeconómicos externos como las proyecciones de tasas en Estados Unidos. El Banco de la República cuenta con herramientas de intervención en caso de que se presenten desviaciones excesivas que puedan afectar la meta de inflación.",
    summaryNeutralized: "La tasa de cambio en Colombia cerró en un promedio de $4.280 COP/USD, tras una jornada de volatilidad influenciada por la tendencia alcista del dólar a nivel global. Las autoridades monitorean la situación para asegurar la estabilidad cambiaria.",
    primaryIntent: 'agitate',
  },
  {
    id: 'a7',
    url: 'https://infobae.com/america/colombia/2026/04/21/milei-petro-enfrentamiento',
    title: 'Milei destruye a Petro en Twitter: la batalla ideológica que sacude América Latina',
    titleNeutralized: 'Milei y Petro intercambian críticas en redes sociales sobre política económica regional',
    excerpt: 'El presidente argentino no dejó pasar la oportunidad de atacar al mandatario colombiano después de sus declaraciones sobre el libre mercado.',
    imageUrl: null, 
    outlet: MEDIA_OUTLETS[6]!,
    journalist: 'Roberto Navarro',
    publishedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    category: 'noticia',
    countryCode: 'AR',
    language: 'es',
    veritasScore: 79,
    analysisStatus: 'completed',
    analysisConfidence: 0.89,
    viewCount: 45600,
    trendingScore: 0.97,
    tags: ['politics', 'international'],
    techniquesDetected: [
      {
        technique: TECHNIQUES[0]!,
        quote: 'destruye a Petro en Twitter',
        confidence: 0.96,
        explanation: '"Destruye" es un verbo de violencia extrema aplicado a un intercambio verbal en redes sociales.',
      },
      {
        technique: TECHNIQUES[2]!,
        quote: 'la batalla ideológica que sacude América Latina',
        confidence: 0.84,
        explanation: 'Presenta el debate política como una "batalla" binaria sacudiendo continente — falsa dicotomía.',
      },
      {
        technique: TECHNIQUES[7]!,
        quote: 'la batalla ideológica que sacude América Latina',
        confidence: 0.71,
        explanation: 'Estructura del titular optimizada para engagement: conflicto + escala continental + personajes conocidos.',
      },
    ],
    content: "La tensión diplomática entre Buenos Aires y Bogotá alcanzó un nuevo pico de intensidad tras una serie de publicaciones cruzadas en la red social X. Todo comenzó cuando el mandatario colombiano cuestionó los resultados de las políticas de austeridad aplicadas en el cono sur, a lo que el presidente argentino respondió con una contundencia inusual. Milei destruye a Petro en Twitter al calificar su visión económica como 'decadente' y 'empobrecedora', marcando lo que muchos analistas llaman la batalla ideológica que sacude América Latina.\n\nEste intercambio no es un hecho aislado, sino parte de una fractura cada vez más profunda entre dos visiones opuestas del estado y el mercado en la región. Mientras Petro aboga por un papel protagónico del sector público en la transición energética y social, Milei sostiene que la única salida para la crisis regional es el desmantelamiento de las trabas estatales. La discusión, aunque digital, tiene repercusiones reales en los foros internacionales como la OEA y el Mercosur.\n\nExpertos en política exterior advierten que esta personalización de las diferencias ideológicas puede entorpecer la integración regional y los acuerdos comerciales necesarios para enfrentar la desaceleración global. Sin embargo, en términos de comunicación política, ambos líderes parecen beneficiarse de esta polarización, consolidando sus respectivas bases electorales mediante la confrontación directa con un 'enemigo' ideológico externo que encarna todo lo que ellos rechazan. El impacto en la opinión pública ha sido inmediato, con millones de interacciones que replican los argumentos de ambos bandos, a menudo sin profundizar en los datos económicos reales que sustentan sus afirmaciones.",
    contentNeutralized: "Los presidentes de Argentina y Colombia mantuvieron un intercambio de opiniones en redes sociales acerca de sus respectivos modelos económicos. El debate surgió a raíz de comentarios sobre el impacto de las políticas de libre mercado en la región, donde ambos mandatarios expusieron sus discrepancias fundamentales sobre el rol del Estado en la economía y la sociedad.\n\nAnalistas de relaciones internacionales sugieren que este tipo de interacciones reflejan las diversas corrientes políticas que conviven actualmente en América Latina. Aunque las diferencias de criterio son evidentes, los canales diplomáticos formales continúan operando para gestionar los asuntos bilaterales de interés común, como el comercio y la cooperación regional. El foco del debate se mantiene en la efectividad de las medidas de ajuste fiscal frente a la inversión social pública como motores de desarrollo.\n\nEn los foros regionales, se observa una tendencia hacia la polarización en los discursos, lo que ha generado debates sobre la necesidad de mantener un diálogo institucional constructivo que trascienda las plataformas digitales. Las proyecciones económicas para ambos países siguen siendo el tema central de preocupación para los organismos multilaterales, quienes instan a la estabilidad política como requisito para el crecimiento sostenido.",
    summaryNeutralized: "Intercambio de críticas entre los presidentes de Argentina y Colombia en redes sociales subraya las diferencias ideológicas en la región. Analistas sugieren que el debate se centra en visiones contrapuestas sobre el mercado y el Estado.",
    primaryIntent: 'inform',
  },
  {
    id: 'a8',
    url: 'https://www.theverge.com/2024/3/13/24099411/european-union-ai-act-passed-parliament',
    title: "EU passes landmark AI Act, setting global rules for artificial intelligence",
    titleNeutralized: "European Parliament approves regulatory framework for Artificial Intelligence (AI Act)",
    excerpt: "The European Union has officially passed the AI Act, the world's first comprehensive set of rules for the AI industry.",
    imageUrl: null, 
    outlet: MEDIA_OUTLETS[7]!,
    journalist: 'Amanda Mars',
    journalistScore: 20,
    publishedAt: '2024-03-13T12:00:00Z',
    category: 'noticia',
    countryCode: 'US',
    language: 'en',
    veritasScore: 12,
    analysisStatus: 'completed',
    analysisConfidence: 0.98,
    viewCount: 15400,
    trendingScore: 0.76,
    tags: ['AI', 'Regulation', 'EU', 'Technology', 'international'],
    techniquesDetected: [
      {
        technique: TECHNIQUES[1]!,
        quote: "landmark AI Act",
        confidence: 0.85,
        explanation: 'The term "landmark" frames the regulation as historic and positive without comparative metrics. Low bias.',
      },
    ],
    content: "In a historic session in Strasbourg, the European Parliament ratified the AI Act with 523 votes in favor, consolidating what many consider the world's most ambitious AI regulation. This regulatory framework establishes risk levels for artificial intelligence applications, specific prohibitions on the use of biometric surveillance systems, and strict transparency obligations for foundational models.\n\nThe new law, which will come into effect progressively over the next two years, seeks to balance technological innovation with the protection of citizens' fundamental rights. Systems considered 'high risk,' such as those used in critical infrastructure, education, or employment, must comply with rigorous technical requirements and permanent human oversight.\n\nGlobal technology companies have expressed concern about the possible impact on European competitiveness compared to powers like the United States and China. However, proponents of the law ensure that this framework will provide the necessary legal certainty for the European AI market to thrive under unmatched ethical standards. The 'Brussels Effect' is expected to influence similar legislation globally, as companies seeking to operate in Europe must adapt their internal processes to these new transparency and safety mandates.",
    contentNeutralized: "The European Parliament has approved the AI Act, a new regulatory framework that classifies artificial intelligence systems according to their risk levels. The legislation includes specific rules for high-risk applications and transparency requirements for large-scale AI models.\n\nExpected to be implemented over the next 24 months, the Act attempts to provide a legal structure for AI development while maintaining consumer protections. High-risk systems will be subject to mandatory documentation and human oversight. While some industry groups have raised questions about its impact on innovation, the EU leadership states that the rules will create a stable environment for ethical AI development. The act serves as the first comprehensive attempt to regulate the industry at such a large scale.",
    summaryNeutralized: "The European Parliament approved the AI Act with a large majority. The regulation introduces a risk management system for AI and sets transparency standards for developers, aiming to protect citizen rights.",
    primaryIntent: 'inform',
  },
  {
    id: 'a9',
    url: 'https://semana.com/nacion/seguridad/eln-negociaciones-fracaso-total',
    title: 'Fracaso total: las negociaciones con el ELN colapsan y Colombia vuelve a la guerra',
    titleNeutralized: 'Negociaciones con el ELN entran en pausa técnica; delegaciones acuerdan retomar en 30 días',
    excerpt: 'El proceso de paz más ambicioso del gobierno Petro se desmorona ante la incapacidad del ejecutivo de cumplir sus propias promesas.',
    imageUrl: null, 
    outlet: MEDIA_OUTLETS[0]!,
    journalist: 'Patricia Montoya',
    journalistScore: 85,
    publishedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    category: 'noticia',
    countryCode: 'CO',
    language: 'es',
    veritasScore: 82,
    analysisStatus: 'completed',
    analysisConfidence: 0.91,
    viewCount: 28900,
    trendingScore: 0.96,
    tags: ['security', 'politics', 'colombia'],
    techniquesDetected: [
      {
        technique: TECHNIQUES[0]!,
        quote: 'Colombia vuelve a la guerra',
        confidence: 0.97,
        explanation: 'Declarar que Colombia "vuelve a la guerra" por una pausa en negociaciones es una hipérbole extrema que activa respuesta de pánico.',
      },
      {
        technique: TECHNIQUES[2]!,
        quote: 'Fracaso total',
        confidence: 0.92,
        explanation: 'Dicotomía absoluta: o el proceso avanza perfectamente o es "fracaso total". Elimina matices de procesos de paz complejos.',
      },
      {
        technique: TECHNIQUES[4]!,
        quote: 'incapacidad del ejecutivo de cumplir sus propias promesas',
        confidence: 0.88,
        explanation: 'Interpreta la pausa técnica como evidencia de incapacidad sin consultar a las delegaciones.',
      },
    ],
    content: "El proceso de paz más ambicioso del gobierno Petro se desmorona ante la incapacidad del ejecutivo de cumplir sus propias promesas. Las delegaciones del Gobierno y del ELN anunciaron hoy una suspensión temporal de la mesa de diálogos en Caracas. Para muchos sectores críticos, esto representa un fracaso total: las negociaciones con el ELN colapsan y Colombia vuelve a la guerra civil abierta.\n\nLa crisis se precipitó tras desacuerdos profundos sobre el cese al fuego bilateral y las recientes operaciones militares en zonas de control histórico de la guerrilla. Mientras el gobierno insiste en que la pausa es necesaria para 'ajustar protocolos', la narrativa de la oposición se centra en la pérdida de control territorial y el aumento de las actividades ilegales durante los periodos de distensión.\n\nEn las regiones más afectadas, como el Catatumbo y el Chocó, la noticia ha generado una ola de escepticismo. Los líderes comunitarios temen que el fin del cese al fuego signifique el regreso de los confinamientos y los desplazamientos masivos que se habían reducido parcialmente durante el último año. La falta de un cronograma claro para el reinicio de las conversaciones mantiene al país en una incertidumbre que amenaza con desestabilizar la política de 'Paz Total' del presidente.",
    contentNeutralized: "Las delegaciones del Gobierno Nacional y del Ejército de Liberación Nacional (ELN) han acordado una pausa técnica en la mesa de diálogos para evaluar el cumplimiento de los acuerdos de cese al fuego. Ambas partes han expresado su compromiso de retomar las conversaciones en un plazo de 30 días, una vez se revisen los protocolos de verificación.\n\nDurante este periodo, los mecanismos de monitoreo regionales continuarán operando para evitar incidentes armados que comprometan la seguridad de la población civil. Las diferencias actuales se centran en la implementación de los proyectos de transformación territorial y la coordinación de las fuerzas de seguridad en áreas específicas.\n\nAnalistas sugieren que este tipo de ajustes son comunes en procesos de negociación de larga duración y alta complejidad. El enfoque del diálogo se mantiene en la participación de la sociedad civil y la búsqueda de soluciones estructurales a los conflictos regionales, mientras se trabaja en la resolución de los puntos de discordia técnica surgidos en el último ciclo.",
    summaryNeutralized: "Gobierno y ELN acuerdan una pausa técnica de 30 días en los diálogos de paz para revisar protocolos del cese al fuego. Ambas delegaciones mantienen su disposición de continuar el proceso una vez resueltos los puntos técnicos.",
    primaryIntent: 'agitate',
  },
  {
    id: 'a10',
    url: 'https://elespectador.com/cultura/feria-libro-bogota-2026-autores',
    title: 'Feria del Libro de Bogotá 2026 rompe récord con 1.2 millones de visitantes',
    titleNeutralized: 'Feria del Libro de Bogotá 2026 rompe récord con 1.2 millones de visitantes',
    excerpt: 'La edición 36 del evento cultural más importante del país cerró con cifras históricas y Colombia Invitada de Honor. Autores de 48 países participaron en más de 800 eventos.',
    imageUrl: null, 
    outlet: MEDIA_OUTLETS[2]!,
    journalist: 'Beatriz González',
    journalistScore: 12,
    publishedAt: new Date(Date.now() - 1000 * 60 * 360).toISOString(),
    category: 'noticia',
    countryCode: 'CO',
    language: 'es',
    veritasScore: 11,
    analysisStatus: 'completed',
    analysisConfidence: 0.97,
    viewCount: 9340,
    trendingScore: 0.55,
    tags: ['culture', 'colombia', 'education'],
    analysisLogs: [
      { stepId: 'nlp', status: 'completed', timestamp: '0.1s', technicalDetail: 'Analyzing entity "ELN" and "Paz Total" policy context.', technicalDetailEs: 'Analizando entidad "ELN" y contexto de política de "Paz Total".' },
      { stepId: 'bert', status: 'completed', timestamp: '0.6s', technicalDetail: 'High intensity score detected on binary "success/failure" framing.', technicalDetailEs: 'Puntaje de alta intensidad detectado en encuadre binario "éxito/fracaso".' },
      { stepId: 'llama', status: 'completed', timestamp: '2.2s', technicalDetail: 'Verifying "collapse" claim vs official "technical pause" statement.', technicalDetailEs: 'Verificando afirmación de "colapso" vs comunicado oficial de "pausa técnica".' },
      { stepId: 'rewrite', status: 'completed', timestamp: '3.3s', technicalDetail: 'Recalibrating headline to reflect procedural status instead of finality.', technicalDetailEs: 'Recalibrando titular para reflejar estatus procedimental en vez de finalidad.' },
      { stepId: 'factcheck', status: 'completed', timestamp: '4.9s', technicalDetail: 'Official delegation communiqué confirms 30-day pause.', technicalDetailEs: 'Comunicado oficial de delegación confirma pausa de 30 días.' },
    ],
    techniquesDetected: [],
    content: "La trigésimo sexta edición de la Feria Internacional del Libro de Bogotá (FILBo) cerró sus puertas superando todas las proyecciones iniciales. Con un total de 1.2 millones de visitantes durante los 15 días del evento, la feria se consolida como el epicentro cultural de la región. Colombia, como invitada de honor en esta edición, destacó la diversidad literaria de sus regiones y el talento de sus nuevos narradores.\n\nEl éxito no solo fue en asistencia, sino también en el sector comercial, con un reporte de crecimiento del 20% en ventas de libros en comparación con el año anterior. La participación de autores de 48 países y la realización de más de 800 eventos académicos y culturales atrajeron a un público diverso, desde niños hasta investigadores especializados. Los pabellones dedicados a la literatura infantil y a la ilustración fueron los más concurridos, reflejando un interés creciente de las nuevas generaciones.\n\nLa Cámara Colombiana del Libro y Corferias, organizadores del evento, atribuyen este récord a una programación más descentralizada y al uso de herramientas digitales para facilitar el acceso a la agenda. 'La FILBo ha dejado de ser solo un mercado de libros para convertirse en un espacio de conversación social fundamental', señalaron en el acto de clausura. La próxima edición ya ha comenzado su fase de planeación, con el reto de mantener estos niveles de participación y seguir democratizando el acceso a la cultura.",
    contentNeutralized: "La Feria Internacional del Libro de Bogotá 2026 finalizó con una asistencia de 1.2 millones de personas, la cifra más alta registrada en su historia. El evento contó con la participación de escritores internacionales de 48 naciones y una amplia oferta de actividades culturales y académicas.\n\nLos reportes preliminares indican un aumento en el volumen de ventas y una alta participación en los talleres educativos. Los organizadores destacan que la programación diversa y las facilidades de acceso contribuyeron al cumplimiento de los objetivos de asistencia. El balance general muestra una tendencia positiva en el consumo de literatura y la asistencia a eventos culturales masivos en la capital colombiana.",
    summaryNeutralized: "La FILBo 2026 cerró con un récord de 1.2 millones de visitantes. El éxito del evento se refleja tanto en la asistencia masiva como en el aumento de ventas y la participación internacional.",
    primaryIntent: 'inform',
  },
  {
    id: 'a11',
    url: 'https://eltiempo.com/bogota/movilidad-metro-bogota-demoras',
    title: 'El Metro de Bogotá: el elefante blanco que nadie quiere pagar',
    titleNeutralized: 'Primera línea del Metro de Bogotá reporta sobrecostos de 12% sobre presupuesto inicial',
    excerpt: 'La obra más costosa de la historia de Colombia acumula retrasos y sobrecostos mientras los bogotanos siguen atrapados en el peor sistema de transporte de América Latina.',
    imageUrl: null, 
    outlet: MEDIA_OUTLETS[3]!,
    journalist: 'Felipe Restrepo',
    journalistScore: 58,
    publishedAt: new Date(Date.now() - 1000 * 60 * 420).toISOString(),
    category: 'noticia',
    countryCode: 'CO',
    language: 'es',
    veritasScore: 56,
    analysisStatus: 'completed',
    analysisConfidence: 0.80,
    viewCount: 16800,
    trendingScore: 0.70,
    tags: ['economy', 'colombia'],
    techniquesDetected: [
      {
        technique: TECHNIQUES[0]!,
        quote: 'el peor sistema de transporte de América Latina',
        confidence: 0.85,
        explanation: 'Superlativo absoluto sin datos de respaldo comparativo entre sistemas de tránsito latinoamericanos.',
      },
    ],
    content: "La construcción de la Primera Línea del Metro de Bogotá avanza en medio de una creciente controversia fiscal. Nuevos informes de auditoría indican que el proyecto ya acumula un sobrecosto del 12% respecto al presupuesto original, lo que para muchos críticos convierte a la obra en el metro de Bogotá: el elefante blanco que nadie quiere pagar. Los retrasos en la adquisición de predios y el traslado de redes han frenado el ritmo de ejecución en varios tramos críticos de la Avenida Caracas.\n\nMientras la administración distrital asegura que estos ajustes son normales en megaobras de esta magnitud, la narrativa pública se ha vuelto cada vez más escéptica. Los bogotanos siguen atrapados en el peor sistema de transporte de América Latina, sufriendo largos tiempos de desplazamiento y hacinamiento en el sistema Transmilenio, que según el cronograma original ya debería estar siendo relevado por el metro.\n\nLa financiación de los tramos faltantes y el debate sobre si una parte de la línea debe ser subterránea continúan dividiendo al gobierno nacional y a la alcaldía. Esta parálisis política, sumada a los desafíos técnicos, plantea serias dudas sobre si la inauguración prevista para finales de la década podrá cumplirse o si el proyecto se sumará a la larga lista de infraestructuras inconclusas en el país.",
    contentNeutralized: "El proyecto de la Primera Línea del Metro de Bogotá presenta un incremento del 12% en sus costos de ejecución, atribuido por la empresa Metro a factores como la gestión predial y la reubicación de redes de servicios públicos. Las obras continúan en desarrollo a lo largo del trazado previsto, con un cronograma que se ajusta a las realidades técnicas encontradas durante la fase de construcción.\n\nEl sistema de transporte actual de la ciudad mantiene su operación habitual mientras se integran los nuevos frentes de obra. El debate técnico actual se enfoca en la optimización de los recursos financieros y la viabilidad de las modificaciones propuestas al diseño original. Las autoridades de transporte trabajan en mitigar el impacto de las obras en la movilidad diaria de los ciudadanos a través de planes de manejo de tráfico específicos.",
    summaryNeutralized: "La Primera Línea del Metro de Bogotá registra sobrecostos del 12% debido a retos técnicos y prediales. Las obras avanzan bajo supervisión, mientras se discuten ajustes presupuestales para asegurar su finalización.",
    primaryIntent: 'inform',
  },
  {
    id: 'a12',
    url: 'https://lasillavacia.com/poder/senado-aprueba-control-acueducto',
    title: 'Senado aprueba en primer debate reforma al código de aguas que afecta 23 municipios',
    titleNeutralized: 'Senado aprueba en primer debate reforma al código de aguas que afecta 23 municipios',
    excerpt: 'La ponencia fue aprobada por 58 a 45 votos y pasa a segundo debate. La reforma modifica el régimen de licencias para captación en cuencas de alta montaña.',
    imageUrl: null, 
    outlet: MEDIA_OUTLETS[1]!,
    journalist: 'Sebastián Lombana',
    journalistScore: 22,
    publishedAt: new Date(Date.now() - 1000 * 60 * 480).toISOString(),
    category: 'noticia',
    countryCode: 'CO',
    language: 'es',
    veritasScore: 19,
    analysisStatus: 'completed',
    analysisConfidence: 0.93,
    viewCount: 5600,
    trendingScore: 0.48,
    tags: ['environment', 'politics', 'colombia'],
    techniquesDetected: [],
    content: "En una votación ajustada que duró más de seis horas, la Comisión Quinta del Senado dio luz verde a la reforma del Código Nacional de Aguas. La iniciativa, que pasa ahora a su segundo debate en plenaria, busca centralizar la administración de las cuencas hidrográficas de alta montaña, una medida que afecta directamente a 23 municipios que actualmente gestionan sus acueductos a través de juntas comunitarias.\n\nLa reforma propone que la Agencia Nacional de Aguas tenga la última palabra sobre las licencias de captación, con el fin de asegurar un flujo mínimo vital ante los efectos del cambio climático. Los opositores de la medida argumentan que esto vulnera la autonomía local y podría abrir la puerta a la privatización del recurso en áreas rurales. Por otro lado, los ponentes del proyecto sostienen que la gestión técnica centralizada es la única forma de evitar conflictos entre departamentos por el acceso al agua en periodos de sequía extrema.\n\nLas organizaciones ambientales han recibido la noticia con cautela. Si bien valoran la intención de proteger las zonas de páramo, advierten que sin una participación real de las comunidades locales, la ley será difícil de implementar en el territorio. El texto de la reforma incluirá en el próximo debate un capítulo especial sobre la protección de los derechos ancestrales de las comunidades indígenas sobre las fuentes hídricas en sus resguardos.",
    contentNeutralized: "La Comisión Quinta del Senado aprobó en primer debate un proyecto de ley para reformar el Código Nacional de Aguas, con un resultado de 58 votos a favor y 45 en contra. La propuesta legislativa establece nuevas directrices para la gestión de cuencas en 23 municipios del país, enfocándose en la coordinación centralizada de las licencias de uso de agua.\n\nEl objetivo de la reforma es fortalecer la seguridad hídrica frente a la variabilidad climática y estandarizar los procesos de captación a nivel nacional. La discusión parlamentaria continuará evaluando el balance entre la autoridad nacional y la autonomía de los acueductos comunitarios. Se espera que en el segundo debate se profundice en los mecanismos de participación ciudadana y la protección de ecosistemas estratégicos de alta montaña.",
    summaryNeutralized: "El Senado avanza en la reforma del Código de Aguas tras aprobarla en primer debate. El proyecto busca centralizar la gestión de licencias hídricas para mejorar la respuesta ante el cambio climático.",
    primaryIntent: 'inform',
  },
  {
    id: 'a13',
    url: 'https://nytimes.com/2026/04/22/us/politics/election-swing-states-polling',
    title: 'Swing States in Chaos: New Polling Suggests Unprecedented Volatility Ahead of November',
    titleNeutralized: 'Latest polling in 6 swing states shows candidates within 2-point margin of error',
    excerpt: 'Voter sentiment in key battlegrounds is shifting rapidly as economic concerns collide with social policy debates, leaving both major parties struggling to secure a definitive lead.',
    imageUrl: null, 
    outlet: MEDIA_OUTLETS[8]!,
    journalist: 'Jonathan Weisman',
    journalistScore: 30,
    publishedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    category: 'noticia',
    countryCode: 'US',
    language: 'en',
    veritasScore: 28,
    analysisStatus: 'completed',
    analysisConfidence: 0.94,
    viewCount: 85400,
    trendingScore: 0.99,
    tags: ['politics', 'usa', 'elections', 'international'],
    techniquesDetected: [
      {
        technique: TECHNIQUES[1]!,
        quote: 'Swing States in Chaos',
        confidence: 0.88,
        explanation: 'Using "Chaos" to describe standard polling fluctuations frames the democratic process as unstable.',
      }
    ],
    content: "With less than seven months until Election Day, the American political landscape is experiencing a level of turbulence that has seasoned strategists on both sides of the aisle scratching their heads. New polling data released today indicates that the race remains a statistical dead heat across six crucial swing states: Pennsylvania, Michigan, Wisconsin, Arizona, Georgia, and Nevada.\n\nThe volatility is driven by a complex intersection of voter priorities. While inflation and the cost of living remain the top concerns for a plurality of voters, recent shifts in social policy discussions—particularly regarding reproductive rights and border security—have re-energized different segments of the electorate. This 'dueling priorities' environment makes it nearly impossible for either candidate to build a sustained lead.\n\nIn Pennsylvania, for instance, a candidate who led by four points in February is now trailing by one point, a shift that is technically within the margin of error but symbolically significant. Analysts point to a growing class of 'double-negative' voters—those who dislike both major party nominees—as the ultimate deciders of the 2026 contest. As both campaigns ramp up advertising spending in these regions, the path to 270 electoral votes remains as obscured as ever.",
    contentNeutralized: "Recent polling data indicates that the upcoming November elections are highly competitive in six key battleground states. In Pennsylvania, Michigan, Wisconsin, Arizona, Georgia, and Nevada, the leading candidates are currently separated by margins ranging from 1 to 2 percentage points, which is within the standard margin of error for such surveys.\n\nVoters cite a variety of issues as their primary concerns, including economic indicators like inflation and policy debates over social issues. Because no single candidate has established a clear lead outside the margin of error, political analysts suggest that undecided voters will play a critical role in the final outcome. Campaigns are increasing their activity in these states as the election cycle progresses.",
    summaryNeutralized: "New polls show a statistical tie in six key US swing states. Both parties are facing a divided electorate concerned with both the economy and social policy, with no clear frontrunner emerging so far.",
    primaryIntent: 'inform',
  },
  {
    id: 'a14',
    url: 'https://cnn.com/2026/04/22/economy/fed-interest-rates-inflation',
    title: 'Fed Trapped: Inflation Data Force Interest Rate Hike as Recession Fears Explode',
    titleNeutralized: 'Federal Reserve increases interest rates by 0.25% following higher-than-expected April CPI report',
    excerpt: 'The Federal Reserve announced a surprising rate increase today, sending shockwaves through Wall Street as policymakers struggle to contain persistent price increases.',
    imageUrl: null,
    outlet: MEDIA_OUTLETS[9]!,
    journalist: 'Matt Egan',
    journalistScore: 40,
    publishedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    category: 'noticia',
    countryCode: 'US',
    language: 'en',
    veritasScore: 45,
    analysisStatus: 'completed',
    analysisConfidence: 0.82,
    viewCount: 120500,
    trendingScore: 0.98,
    tags: ['economy', 'usa', 'finance', 'international'],
    techniquesDetected: [
      {
        technique: TECHNIQUES[0]!,
        quote: 'Recession Fears Explode',
        confidence: 0.92,
        explanation: 'The verb "Explode" is an emotional intensifier used to generate panic despite stable GDP growth.',
      }
    ],
    content: "The Federal Reserve took aggressive action today, raising its benchmark interest rate by a quarter percentage point in a move that few economists predicted just a week ago. The decision comes on the heels of the latest Consumer Price Index (CPI) report, which showed inflation remains stubbornly high at 3.4% annually, well above the Fed's 2% target.\n\nFed Chair Jerome Powell, in a somber press conference, indicated that 'the road to price stability remains longer and more winding than previously anticipated.' This hawkish pivot sent Wall Street into a tailspin, with the Dow Jones Industrial Average dropping nearly 600 points within minutes of the announcement. Critics argue that the central bank is now 'trapped' between the need to crush inflation and the risk of triggering a deep recession.\n\nFor American families, the move means borrowing costs for mortgages, credit cards, and auto loans will continue to climb. While the labor market remains resilient, some sectors—particularly tech and manufacturing—are already feeling the squeeze of higher capital costs. The debate now shifts to whether the Fed can achieve the elusive 'soft landing' or if the US economy is headed for a more painful contraction later this year.",
    contentNeutralized: "The Federal Reserve has raised interest rates by 25 basis points (0.25%) in response to new data showing that inflation remains at 3.4% annually. The Federal Reserve's stated goal is to bring inflation down to a target rate of 2%.\n\nFollowing the announcement, major stock market indices experienced a decline. Chair Jerome Powell noted that further adjustments may be necessary to achieve price stability. This increase will lead to higher interest rates for consumer loans and mortgages. While some sectors of the economy show signs of slowing due to higher borrowing costs, the overall labor market remains stable. Economists continue to monitor whether these measures will successfully control inflation without causing a significant economic downturn.",
    summaryNeutralized: "The Federal Reserve raised interest rates by 0.25% to combat persistent 3.4% inflation. This move increases borrowing costs for consumers and led to a temporary stock market dip, as the Fed continues its efforts to reach a 2% inflation target.",
    primaryIntent: 'inform',
  },
  {
    id: 'a15',
    url: 'https://foxnews.com/2026/04/22/border-security-crisis-national-sovereignty',
    title: 'National Sovereignty at Risk: Border Crossings Reach Catastrophic Levels as Washington Fails to Act',
    titleNeutralized: 'Border patrol reports 15% increase in monthly encounters at Southern Border',
    excerpt: 'Unprecedented numbers of migrants are overwhelming border communities, creating a security and humanitarian crisis that many believe is being ignored by federal authorities.',
    imageUrl: null,
    outlet: MEDIA_OUTLETS[10]!,
    journalist: 'Bill Melugin',
    journalistScore: 82,
    publishedAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    category: 'noticia',
    countryCode: 'US',
    language: 'en',
    veritasScore: 88,
    analysisStatus: 'completed',
    analysisConfidence: 0.95,
    viewCount: 340000,
    trendingScore: 0.97,
    tags: ['security', 'usa', 'immigration', 'international'],
    techniquesDetected: [
      {
        technique: TECHNIQUES[0]!,
        quote: 'Catastrophic Levels',
        confidence: 0.98,
        explanation: 'Extreme hyperbole designed to activate the biological fear response (amygdala) regarding group safety.',
      },
      {
        technique: TECHNIQUES[4]!,
        quote: 'Washington Fails to Act',
        confidence: 0.91,
        explanation: 'Frames the issue as a deliberate failure by specific political actors to engineer moral outrage.',
      }
    ],
    content: "The situation at the Southern Border has reached what local sheriffs are calling a 'breaking point' that threatens the very fabric of national sovereignty. New data obtained by Fox News shows that illegal crossings have surged to catastrophic levels this month, with border agents recording over 250,000 encounters—the highest number in recorded history.\n\nBorder towns are currently overwhelmed, with local resources for housing, medical care, and processing stretched beyond capacity. In Eagle Pass, Texas, the mayor has declared a local state of emergency as hundreds of migrants continue to cross the Rio Grande daily. 'We are being left to fend for ourselves,' one resident said. 'Washington has completely abandoned us in favor of political optics.'\n\nWhile federal officials point to seasonal trends and regional instability as the primary drivers, critics argue that current enforcement policies are actively encouraging the surge. The humanitarian toll is also rising, with reports of dangerous conditions for those making the journey. As the debate in D.C. remains deadlocked over funding and policy changes, those on the front lines say the crisis is no longer manageable and requires immediate, decisive action to restore order.",
    contentNeutralized: "U.S. Customs and Border Protection reports that encounters at the Southern Border reached approximately 250,000 this month, representing a 15% increase compared to previous records. This increase has placed significant demand on local and federal resources in border communities.\n\nSeveral border municipalities, including Eagle Pass, Texas, have issued local emergency declarations to manage the influx of individuals and allocate necessary housing and medical services. Federal authorities attribute the current trend to a combination of seasonal migration patterns and socio-economic instability in Central and South America. Meanwhile, there is ongoing debate in the U.S. Congress regarding border security funding and immigration policy, with varying proposals on how to manage the border and process asylum seekers.",
    summaryNeutralized: "Border encounters reached a record 250,000 this month, leading some local Texas officials to declare emergencies. Federal data shows a significant increase in migration, sparking continued political debate over enforcement and humanitarian resources.",
    primaryIntent: 'agitate',
  },
]

// ── Utility functions ──────────────────────────────────────

export function getArticlesByCountry(countryCode: string): Article[] {
  if (countryCode === 'ALL') return MOCK_ARTICLES
  return MOCK_ARTICLES.filter((a) => a.countryCode === countryCode)
}

export function getArticlesByTopics(topics: string[]): Article[] {
  if (!topics.length) return MOCK_ARTICLES
  return MOCK_ARTICLES.filter((a) =>
    a.tags.some((tag) => topics.includes(tag))
  )
}

export function getTrendingArticles(limit = 10): Article[] {
  return [...MOCK_ARTICLES]
    .sort((a, b) => b.trendingScore - a.trendingScore)
    .slice(0, limit)
}

export function getArticleById(id: string): Article | undefined {
  return MOCK_ARTICLES.find((a) => a.id === id)
}

export function simulateInfiniteScroll(
  page: number,
  perPage = 9,
  countryCode = 'CO',
  topicSlugs: string[] = []
): { articles: Article[]; hasMore: boolean; nextPage: number } {
  // Filter by country first - BE STRICTER
  let pool = countryCode === 'ALL'
    ? MOCK_ARTICLES
    : MOCK_ARTICLES.filter(
        (a) => a.countryCode === countryCode
      )

  // If pool is empty for a specific country (rare but possible), add international articles
  if (pool.length === 0 && countryCode !== 'ALL') {
    pool = MOCK_ARTICLES.filter(
      (a) => a.tags.includes('international') || a.countryCode === 'ALL'
    )
  }

  // Filter by topics
  if (topicSlugs.length > 0) {
    pool = pool.filter((a) =>
      a.tags.some((tag) => topicSlugs.includes(tag))
    )
  }

  // Sort by trending
  pool = [...pool].sort((a, b) => b.trendingScore - a.trendingScore)

  // Shuffle the pool for a more "live" feel if it's the first page or we are in mock mode
  // This prevents the user from seeing the same 5 news in the same order
  const shuffledPool = [...pool].sort(() => Math.random() - 0.5)

  // Paginate
  const slice = []
  const startIdx = (page - 1) * perPage
  
  for (let i = 0; i < perPage; i++) {
    const idx = (startIdx + i) % shuffledPool.length
    const article = shuffledPool[idx]
    if (article) {
      slice.push({
        ...article,
        id: `${article.id}-p${page}-${i}-${Math.random().toString(36).slice(2, 5)}`,
        publishedAt: new Date(
          Date.now() - 1000 * 60 * (i * 15 + page * 60)
        ).toISOString(),
        viewCount: article.viewCount + Math.floor(Math.random() * 1000),
      })
    }
  }

  return {
    articles: slice,
    hasMore: page < 8, 
    nextPage: page + 1,
  }
}
